# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: Akash's portifolio page # Website name
baseurl: https://akashtadwai.netlify.app/ # Website URL
copyright: '©2023 akash_tadwai' # Footer text, e.g. '© {year} Me'

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## MODULES
############################

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5

enableEmoji: true
cascade:
  # Configure blog posts
  - _target:
      path: /posts/**
    pager: true
    reading_time: true
    commentable: true
    show_related: true
    show_breadcrumb: true
    share: true
    header:
      navbar:
        enable: false
header:
  navbar:
    block: navbar
    enable: true
    show_search: true
    highlight_active_link: true 

features:
  comment:
    # Choose a provider: giscus, disqus, commento, or '' to disable commenting
    provider: 'disqus'
    disqus:
      # Paste the shortname from your Disqus dashboard.
      shortname: 'https-akashtadwai-netlify-app'
      # Show comment count in page header? (true/false)
      show_count: true

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
favicon: "/favicon.ico"
paginate: 10
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  event: '/talk/:slug/'
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep

customtextFontFamily : "Hanken Grotesk"
customheadingFontFamily : "Fraunces"
# alternatively, leave empty and select basic font options: sans-serif or serif
# for more http://tachyons.io/docs/typography/font-family/
textFontFamily : "sans-serif"
headingFontFamily : "sans-serif"